### ISSUE TITLE
Bazel Steward

### ISSUE THREAD

**Issue by vorburger** [enola-dev/enola#254]
https://github.com/marketplace/actions/bazel-steward

https://github.com/VirtusLab/bazel-steward

https://virtuslab.github.io/bazel-steward/

**Comment by vorburger** [comment]
https://virtuslab.github.io/bazel-steward/#locally

**Comment by vorburger** [comment]
> https://virtuslab.github.io/bazel-steward/#locally

    coursier launch org.virtuslab:bazel-steward:1.5.0 --main org.virtuslab.bazelsteward.app.Main -- --no-remote --analyze-only

does:

```
[main] INFO org.virtuslab.bazelsteward.app.App - Update suggestions (1):
bazel 8.0.1 -> 8.1.0
[DefaultDispatcher-worker-2] INFO org.virtuslab.bazelsteward.core.common.CommandRunner - bazel mod graph --depth=1
[main] WARN org.virtuslab.bazelsteward.app.App - Error happened during detecting available versions for bzlmod. Skipping this dependency kind...
[main] WARN org.virtuslab.bazelsteward.app.App - Error details: bazel mod graph --depth=1
<root> (@_)
├───gazelle@0.40.0
├───googleapis@0.0.0-20240819-fe8ba054a
├───grpc-java@1.69.0
├───protobuf@29.2
├───rules_go@0.51.0
├───rules_java@8.9.0
└───rules_jvm_external@6.6


 no actions running
ERROR: Traceback (most recent call last):
        File "/home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_apple+/apple/internal/apple_xcframework_import.bzl", line 775, column 21, in <toplevel>
                apple_common.AppleDynamicFramework,
Error: 'struct' value has no field or method 'AppleDynamicFramework'
Available attributes: Objc, XcodeProperties, XcodeVersionConfig, apple_host_system_env, apple_platform, apple_toolchain, compilation_support, dotted_version, get_apple_config, get_cpu, get_split_build_configs, get_split_prerequisites, new_objc_provider, platform, platform_type, target_apple_env
ERROR: @@bazel_tools//tools/cpp:cc_configure.bzl does not export a module extension called cc_configure_extension, yet its use is requested at https://bcr.bazel.build/modules/abseil-cpp/20240722.0/MODULE.bazel:23:29
ERROR: Error loading '@@rules_apple+//apple:apple.bzl' for module extensions, requested by https://bcr.bazel.build/modules/rules_apple/3.5.1/MODULE.bazel:27:48: at /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_apple+/apple/apple.bzl:27:5: initialization of module 'apple/internal/apple_xcframework_import.bzl' failed: at /home/vorburger/.cache/bazel/_bazel_vorburger/a3cf8df34f0c7a76e9926daaad9ffbf4/external/rules_apple+/apple/apple.bzl:27:5: initialization of module 'apple/internal/apple_xcframework_import.bzl' failed
ERROR: Results may be incomplete as 2 extensions failed.

[main] INFO org.virtuslab.bazelsteward.app.App - Update suggestions (0):

[DefaultDispatcher-worker-2] INFO org.virtuslab.bazelsteward.core.common.CommandRunner - bazel build @all_external_repositories//:result.json
[main] WARN org.virtuslab.bazelsteward.app.App - Error happened during detecting available versions for bazel-rules. Skipping this dependency kind...
[main] WARN org.virtuslab.bazelsteward.app.App - Error details: bazel build @all_external_repositories//:result.json

Computing main repo mapping:
Loading:
Loading: 0 packages loaded
WARNING: Target pattern parsing failed.
ERROR: Skipping '@all_external_repositories//:result.json': No repository visible as '@all_external_repositories' from main repository
ERROR: No repository visible as '@all_external_repositories' from main repository
INFO: Elapsed time: 0.089s
INFO: 0 processes.
ERROR: Build did NOT complete successfully

[main] INFO org.virtuslab.bazelsteward.app.App - Update suggestions (0):

[DefaultDispatcher-worker-2] INFO org.virtuslab.bazelsteward.core.common.CommandRunner - bazel query @maven//:outdated.repositories --output xml --noshow_progress
[main] ERROR org.virtuslab.bazelsteward.maven.MavenDependencyKind - Failed to extract used maven dependencies. Bazel Steward supports rules_jvm_external 4.0 or newer
[main] WARN org.virtuslab.bazelsteward.app.App - Error happened during detecting available versions for maven. Skipping this dependency kind...
[main] WARN org.virtuslab.bazelsteward.app.App - Error details: bazel query @maven//:outdated.repositories --output xml --noshow_progress

ERROR: No repository visible as '@maven' from main repository
```

https://github.com/VirtusLab/bazel-steward/issues/401 created about this.

**Comment by vorburger** [comment]
I've played with this again today, and with it so far manually got #1147 (🚀) ; for full automation remaining TODO:

- [ ] [Add Post Update Hook to PIN](https://virtuslab.github.io/bazel-steward/docs/configuration/configuration-file/maven.html) (`REPIN=1 bazelisk run @enola_maven//:pin`) in #1145
- [ ] https://github.com/VirtusLab/bazel-steward/issues/403 would need to be fixed (this is blocking, because it "corrupts" fiels)
- [ ] https://github.com/VirtusLab/bazel-steward/issues/404 would need to be fixed (this is blocking, because it proposes an invalid version)
- [ ] https://github.com/enola-dev/enola/issues/1146 should but doesn't have to be fixed (it would just "miss" module upgrads)
- [ ] [Enable GitHub Action](https://virtuslab.github.io/bazel-steward/docs/installation.html)
- [ ] PR to add Enola to [Bazel Steward Community](https://virtuslab.github.io/bazel-steward/docs/community.html) 🍭 

@lukaszwawrzyk Thank You for Bazel Steward!

**Comment by vorburger** [comment]
FTR, https://github.com/enola-dev/enola/branches/all?query=bazel-steward (currently) has:

* bazel-steward/org.apache.maven.resolver/maven-resolver-util/2.0.7
* bazel-steward/org.apache.maven.resolver/maven-resolver-api/2.0.7
* bazel-steward/com.github.spotbugs/spotbugs-annotations/4.9.2
* bazel-steward/io.github.amithkoujalgi/ollama4j/1.0.94
* bazel-steward/io.kubernetes/client-java/23.0.0
* bazel-steward/com.google.api.grpc/proto-google-cloud-pubsub-v1/1.119.1
* bazel-steward/rules_go/0.53.0

So once [the WIP GitHub Action](https://github.com/enola-dev/enola/blob/fd150c531c6f351ae89459e238e8d5eb84565b14/.github/workflows/bazel-steward.yaml#L17) works, it should normally create 7 PRs...
